sudo: false
language: node_js
node_js:
- 10
cache: npm
branches:
  only:
  - deploy
script:
- hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  on:
    branch: deploy
  local-dir: docs
before_install:
- openssl aes-256-cbc -K $encrypted_3aae978f1794_key -iv $encrypted_3aae978f1794_iv
  -in deploy_key.enc -out ./deploy_key -d
